language: node_js
node_js:
  - 12

install:
  - npm install -g s3-deploy
  - npm install

script:
  - npm run lint
  - echo "write some tests..."

before_deploy:
  - npm install -g s3-deploy

deploy:
  provider: script
  script: npm install && npm run clean && npm run build && s3-deploy './dist/**' --cwd './dist/' --region $AWS_REGION --bucket $AWS_S3_BUCKET
  on:
    tags: true